[package]
name = "kernelspace"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernelspace-component"
path = "src/main.rs"

[build-dependencies]
which = { workspace = true }

[dependencies]
aya-ebpf = { workspace = true }
