[toolchain]
channel = "nightly"
profile = "default"
components = [
  "rust-analyzer",
  "rust-src",
  "rustfmt",
  "cargo",
  "clippy",
  "rust-docs",
  "rust-std",
  "rustc",
]
targets = [ "x86_64-unknown-linux-gnu" ]
